#! /bin/sh
#

### BEGIN INIT INFO
# Provides:          tcos-multi
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=tcos-multi
DESC="Compatibility script to launch legacy (=TCOS<2.0) tcos boot scripts on run level 2345"

SCRIPT_DIRS_OPT=/opt/*/tcos/rc2345.d

# CONSTANTS ###############################################
# Reset fb color mode
RESET="]R"
# ANSI COLORS
# Erase to end of line
CRE="
[K"
# Clear entire screen
CLEAR="[H[J"
# Normal color
NORMAL="[0;39m"
# RED: Failure or error message
RED="[1;31m"
# GREEN: Success message
GREEN="[1;32m"
# YELLOW: Descriptions
YELLOW="[1;33m"
# BLUE: System mesages
BLUE="[1;34m"
# MAGENTA: Found devices or drivers
MAGENTA="[1;35m"
# CYAN: Questions
CYAN="[1;36m"
# BOLD WHITE: Hint
WHITE="[1;37m"

# Get LSB functions
. /lib/lsb/init-functions 
. /etc/default/rcS

runparts_opt() {
        ERRORLEVEL=0
        for dir in $SCRIPT_DIRS_OPT; do
                if [ -d "$dir" ]; then
                    run-parts "$dir"
                    if [ $? -ne 0 ]; then
                          #ERRORLEVEL=65
                          echo -e "\n\tAt least one script in folder\n\t\t${dir}\n${RED}\tfailed.${NORMAL}"
                          sleep 1
                    fi
                fi
        done
        #return $ERRORLEVEL
        return 0
}

case "$1" in
  start)
	log_begin_msg "Running TCOS rc2345.d scripts."
	if runparts_opt; then
		log_end_msg 0
	else
		log_end_msg $?
	fi
	;;
  stop)
    ;; 
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
