#!/bin/sh

PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

# find total amount of available ram
TOTAL_RAM=$( grep MemTotal /proc/meminfo |tr -d ': [A-Z][a-z]')

# Do not use compcache if more than 128MB RAM available
if [ "${TOTAL_RAM}" -gt 131072 ]; then
    exit 0
fi

modprobe -q --ignore-install compcache compcache_size_kbytes="65536"
